CREATE TABLE "USERNAME"."movie"(
	name VARCHAR(20) NOT NULL PRIMARY KEY, 
	address VARCHAR(80) NOT NULL, 
	creditLine DECIMAL(10, 2) NOT NULL, 
	phone VARCHAR(20) NOT NULL
);
CREATE TABLE "USERNAME"."product"(
	productName VARCHAR(20) NOT NULL PRIMARY KEY, 
	price DECIMAL(10, 2) NOT NULL, 
	stock INT NOT NULL
);
CREATE TABLE "USERNAME"."order"(
	orderId BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	retailerName VARCHAR(20) NOT NULL REFERENCES "USERNAME"."retailer"(name), 
	orderDate DATE NOT NULL, 
	orderPrice DECIMAL(10, 2) NOT NULL, 
	status VARCHAR(20)
);
CREATE TABLE "USERNAME"."orderLine"(
	orderLineId BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	orderId BIGINT NOT NULL REFERENCES "USERNAME"."order"(orderId), 
	price DECIMAL(10, 2) NOT NULL, 
	productName VARCHAR(20) NOT NULL REFERENCES "USERNAME"."product"(productName), 
	quantity INT NOT NULL
);