CREATE TABLE "USERNAME"."film"(
	filmId BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	title VARCHAR(40) NOT NULL,
	country VARCHAR(2) NOT NULL,
	syncronized VARCHAR(1) NOT NULL,
	director VARCHAR(50) NOT NULL,
	storyline VARCHAR(300) NOT NULL, 
	runtime INT NOT NULL,
	licenseToPlay INT NOT NULL,
	ageLimit VARCHAR(1) NOT NULL
);
CREATE TABLE "USERNAME"."show"(
	showId BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	filmId BIGINT NOT NULL REFERENCES "USERNAME"."film"(filmId),
	roomName VARCHAR(30) NOT NULL REFERENCES "USERNAME"."room"(roomName),
	startAtDatetime DATE NOT NULL
);
CREATE TABLE "USERNAME"."room"(
	roomName VARCHAR(30) NOT NULL PRIMARY KEY,
	rowNr INT NOT NULL;
	columnNr INT NOT NULL
);
CREATE TABLE "USERNAME"."seat"(
	seatId BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	showId BIGINT NOT NULL REFERENCES "USERNAME"."show"(showId),
	roomName VARCHAR(30) NOT NULL REFERENCES "USERNAME"."room"(roomName),
	rowIdx INT NOT NULL,
	columnIdx INT NOT NULL
);

